//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelOData.VisualWebPart1 {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class VisualWebPart1 {
        
        public static implicit operator global::System.Web.UI.TemplateControl(VisualWebPart1 target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::ExcelOData.VisualWebPart1.VisualWebPart1 @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<script type=\"text/javascript\" language=\"javascript\" src=\"/_layouts/15/Exce" +
                        "lOData/jquery-1.6.2.min.js\"></script>\r\n\r\n<div id=\"resultsDiv\">Loading...</div>\r\n" +
                        "\r\n<script type=\"text/javascript\">\r\n    $(document).ready(function () {\r\n        " +
                        "var e = ExecuteOrDelayUntilScriptLoaded(showSheet, \"sp.js\");\r\n    });\r\n\r\n    fun" +
                        "ction showSheet() {\r\n\r\n        Results = {\r\n            element: \'\',\r\n          " +
                        "  url: \'\',\r\n\r\n            init: function (element) {\r\n                Results.el" +
                        "ement = element;\r\n                Results.url = _spPageContextInfo.webAbsoluteUr" +
                        "l + \"/_vti_bin/ExcelRest.aspx/Shared%20Documents/MiniCRM.xlsx/OData/Table1\";\r\n  " +
                        "          },\r\n\r\n            load: function () {\r\n                $.ajax(\r\n      " +
                        "              {\r\n                        url: Results.url,\r\n                    " +
                        "    method: \"GET\",\r\n                        headers: {\r\n                        " +
                        "    \"accept\": \"application/json\",\r\n                        },\r\n                 " +
                        "       success: Results.onSuccess,\r\n                        error: Results.onErr" +
                        "or\r\n                    }\r\n                );\r\n            },\r\n\r\n            onS" +
                        "uccess: function (data) {\r\n                var results = data.d.results;\r\n      " +
                        "          var html = \"<table>\";\r\n\r\n                for (var i = 0; i < results.l" +
                        "ength; i++) {\r\n                    html += \"<tr><td>\";\r\n                    html" +
                        " += results[i].ns1FullName;\r\n                    html += \"</td><td>\"\r\n          " +
                        "          html += results[i].ns1Email;\r\n                    html += \"</td><tr>\";" +
                        "\r\n                }\r\n\r\n                html += \"</table>\";\r\n                Resu" +
                        "lts.element.html(html);\r\n            },\r\n\r\n            onError: function (err) {" +
                        "\r\n                alert(JSON.stringify(err));\r\n            }\r\n        }\r\n\r\n     " +
                        "   Results.init($(\'#resultsDiv\'));\r\n        Results.load();\r\n    }\r\n</script>\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
