//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateResearchLibraries.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateResearchLibraries.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Product_Design_Specification_docx {
            get {
                object obj = ResourceManager.GetObject("Product_Design_Specification_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Product_Plan_Schedule_xlsx {
            get {
                object obj = ResourceManager.GetObject("Product_Plan_Schedule_xlsx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XmlDocuments&gt;
        ///
        ///  &lt;XmlDocument NamespaceURI=&quot;http://schemas.microsoft.com/office/documentsets/sharedfields&quot;&gt;
        ///    &lt;SharedFields xmlns=&quot;http://schemas.microsoft.com/office/documentsets/sharedfields&quot; /&gt;
        ///  &lt;/XmlDocument&gt;
        ///  
        ///  &lt;XmlDocument NamespaceURI=&quot;http://schemas.microsoft.com/office/documentsets/welcomepagefields&quot;&gt;
        ///    &lt;WelcomePageFields xmlns=&quot;http://schemas.microsoft.com/office/documentsets/welcomepagefields&quot; /&gt;
        ///  &lt;/XmlDocument&gt;
        ///  
        ///  &lt;XmlDocument NamespaceURI=&quot;http://schemas.microsoft.com/offic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductPlanContentType_xml {
            get {
                return ResourceManager.GetString("ProductPlanContentType_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WingtipProductPlanStatusReport_dotx {
            get {
                object obj = ResourceManager.GetObject("WingtipProductPlanStatusReport_dotx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WingtipProductProposal_dotx {
            get {
                object obj = ResourceManager.GetObject("WingtipProductProposal_dotx", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
